# Enable mouse 
set -g mouse on

# Set the default terminal type to support 256 colors
set -g default-terminal "screen-256color"

# Tell tmux to enable True Color (24-bit) support for your outside terminal
set-option -sa terminal-overrides ",xterm*:Tc"
